#zh_CN / en_US
language: "zh_CN"
MySQL:
  enable: false
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "12345678"
  database: "s_team_sys"
Redis:
  enable: false
  host: "127.0.0.1"
  port: 6379
#  user: "root"         # comment it if not used / 如果不需要就注释掉
#  password: "114514"
Distribute:           # 群组配置，多服之间互通需要打开
  enable: false
  id: "team_sys_1"    # 群组服中标记此服的唯一 id
  type: "master"      # master -> 主服  slave -> 子服   只能有一个主服
  host: "127.0.0.1"   # master 节点的 ip
  port: 11451         # master 节点的端口 (这不是游戏的端口，master 节点配置时这个端口不能被占用)
  exposed_host: "192.168.35.8"  # 服务器向外暴露的 host | 平时玩家连服务器用的 IP | 如果使用 waterdogpe 配置为这个服的名称