name: TeamSystem
main: cn.lanink.teamsystem.TeamSystem
version: "1.0.0-SNAPSHOT"
api: ["1.0.11"]
load: POSTWORLD
authors: ["LT_Name", "SmallasWater"]
depend:
  - "MemoriesOfTime-GameCore"
  - "EasyMySQL"

commands:
  team:
    description: "TeamSystem组队系统"
    usage: "/team"
    permission: teamsystem.user

permissions:
  teamsystem.user:
    default: true